versions:
  "0.2.8":
    folder: all
  "0.2.7":
    folder: all
  "0.2.5":
    folder: all
  "0.2.4":
    folder: all
  "0.2.3":
    folder: all
  "0.2.2":
    folder: all
  "0.2.0":
    folder: all
  "0.1.0":
    folder: all
